### PR TITLE
Added the changes for the new script based setup

### PR DESCRIPTION
**Pull request by mondain**

### CODE REVIEW

**Comment by mrchrisallen** [comment]
For some reason the images you added aren't showing up in the markdown readme file.

**Comment by mondain** [comment]
I uploaded them to the images folder, I'm not sure why they dont show up, unless its because they aren't part of the PR

**Comment by mondain** [comment]
Also I attached the build.zip that has the script in it to the jira ticket; you can also grab it from here: https://www.dropbox.com/s/htpc7eza5v0xr6p/build.zip?dl=0

**Comment by mondain** [comment]
It took more than an hour, but I think the final resulting script is dope!

**Pull request merged**
